version: '3.7'

services:
  locaweb_tweets:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: ${ENV}
    environment:
      RAILS_LOG_TO_STDOUT: 'yes'
      RAILS_ENV: ${ENV}
      HTTP_USERNAME: ${HTTP_USERNAME}
    ports:
      - 3000:3000
    networks:
      - dmz
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]

networks:
  dmz:
    external: true
    name: dmz
